Import fenix quarantine
mozilla-l10n/android-l10n pull request #646
Opened 2023-04-26 15:12 UTC by mozilla-pontoon

Import fenix quarantine

2023-04-26 15:12 UTC, mozilla-pontoon commented
Run ID: 4810361291

## TOML file: firefox.toml

### File: mozilla-mobile/fenix/app/src/main/res/values/strings.xml

**ID**: `juno_onboarding_default_browser_description_nimbus`
**Text**: `Firefox puts people over profits and defends your privacy by blocking cross-site trackers.\n\nLearn more in our privacy policy.`
**Errors:**
- Hard-coded brand `Firefox`. Use a variable instead.

**ID**: `juno_onboarding_default_browser_title_nimbus`
**Text**: `Make Firefox your go-to browser`
**Errors:**
- Hard-coded brand `Firefox`. Use a variable instead.

**Total errors not yet reported:** 2

2023-04-27 01:02 UTC, Delphine requested changes
@t-p-white: Pinging you since you landed the strings. Just a few quick fixes. Thank you!

2023-04-27 01:16 UTC, Delphine requested changes
(sorry for both pings, didn't realize I had already posted a review above)
@t-p-white: Pinging you here since I see you landed these two strings. There are just a few quick fixes needed, thank you!

(Note to self: I'll add exceptions for these two strings since "Firefox" isn't a placeholder)

2023-04-27 01:16 UTC, Delphine commented on mozilla-mobile/fenix/app/src/main/res/values/strings.xml
> +        Note: The word 'Firefox' should NOT be translated -->
Nit: should be "Title **to** set Firefox..." etc

2023-04-27 02:02 UTC, mozilla-pontoon commented
Run ID: 4810361291

## TOML file: firefox.toml

### File: mozilla-mobile/fenix/app/src/main/res/values/strings.xml

**ID**: `juno_onboarding_default_browser_description_nimbus`
**Text**: `Firefox puts people over profits and defends your privacy by blocking cross-site trackers.\n\nLearn more in our privacy policy.`
**Errors:**
- Hard-coded brand `Firefox`. Use a variable instead.

**ID**: `juno_onboarding_default_browser_title_nimbus`
**Text**: `Make Firefox your go-to browser`
**Errors:**
- Hard-coded brand `Firefox`. Use a variable instead.

**Total errors not yet reported:** 2

2023-04-27 05:17 UTC, flodolo commented
Side note: the linter is behaving weirdly (not CCing the author) because, for some reason, those strings landed without an author.

Notice the icons [here](https://github.com/mozilla-mobile/firefox-android/commits/main/fenix/app/src/main/res/values/strings.xml) 

<img width="661" alt="Screenshot 2023-04-27 alle 07 14 53" src="https://user-images.githubusercontent.com/3644868/234765630-8fd77c4f-e1a3-4285-9765-defb03d8be65.png">

That might be also causing the comment to be repeated, but I'd need to verify that.

2023-04-27 08:33 UTC, t-p-white commented on mozilla-mobile/fenix/app/src/main/res/values/strings.xml
> +        Note: The word 'Firefox' should NOT be translated -->
Thanks for the feedback @Delphine 👍 I've added 'experiment' to the comment.

> Nit: should be "Title to set Firefox..." etc

I think **for** is correct here as it is describing a title for a 'type' of screen. Please see the lines 290-328 for more examples

2023-04-27 15:12 UTC, mozilla-pontoon commented
Run ID: 4821434875

## TOML file: firefox.toml

### File: mozilla-mobile/fenix/app/src/main/res/values/strings.xml

**ID**: `juno_onboarding_enable_notifications_description_nimbus`
**Text**: `Send tabs between devices, manage downloads, and get tips on getting the most out of Firefox.`
**Errors:**
- Hard-coded brand `Firefox`. Use a variable instead.

**ID**: `juno_onboarding_enable_notifications_title_nimbus`
**Text**: `Notifications help you do more with Firefox`
**Errors:**
- Hard-coded brand `Firefox`. Use a variable instead.

**Total errors not yet reported:** 2

2023-04-27 21:01 UTC, Delphine approved these changes

2023-04-27 21:04 UTC, Delphine commented
Ah just realized linter is still complaining because of the two new strings with "Firefox" in them. I'll add those to exceptions as well now

2023-04-27 22:09 UTC, merged